### ISSUE TITLE
detetctor spctrum

### ISSUE THREAD

**Issue by omrghad** [xcist/main#106]
Dear all,
 please i want to measure the detector spectrum, i tried by raising  applied what you said in issue #37, but i did not get the output, how can i resolve this issue please?
 regards

**Comment by zhangjy-ge** [comment]
If you follow the steps in #37 you should be able to get `thisSubView` that can be reshaped to `[detectorColCount*detectorRowCount, physics.energyCount]`, which is the detector spectrum.

What do you mean by "not get the output"? This seems weird to me.

**Comment by omrghad** [comment]
this is my code: 
def Detection_EI(cfg, viewId, subViewId):

    Evec = cfg.sim.Evec
        
    # detection efficiency
    if viewId == cfg.sim.startViewId and subViewId == 0:
        # detector prefilter
        cfg.sim.Wvec = feval(cfg.physics.prefilterCallback, cfg)
        
        # detector absorption
        detectorMu = GetMu(cfg.scanner.detectorMaterial, Evec)
        detEff = 1-np.exp(-0.1*cfg.scanner.detectorDepth/np.cos(cfg.det.betas)*detectorMu)

        np.multiply(cfg.sim.Wvec, detEff, out=cfg.sim.Wvec)
        
    # Apply energy-dependent detection efficiency
    np.multiply(cfg.thisSubView, cfg.sim.Wvec,  out=cfg.thisSubView)
    
    # scatter cross-talk
    if cfg.physics.crosstalkCallback:
        cfg.thisSubView = feval(cfg.physics.crosstalkCallback, cfg.thisSubView, cfg)
        
    # quantum noise
    if cfg.sim.enableQuantumNoise:
        cfg.thisSubView = randpf(cfg.thisSubView)
        
    # merge energies
    thisSubView = cfg.thisSubView.dot(Evec)
        
    # lag
    if cfg.physics.lagCallback:
        thisSubView = feval(cfg.physics.lagCallback, thisSubView, viewId, subViewId, cfg)

    # accumulate subviews
    if subViewId == 0:
        cfg.thisView = thisSubView
    else:
        cfg.thisView += thisSubView
        
    # for final subview
    if subViewId == cfg.sim.subViewCount-1:
        # optical cross-talk
        if cfg.physics.opticalCrosstalkCallback:
            cfg.thisView = feval(cfg.physics.opticalCrosstalkCallback, cfg.thisView, cfg)
        
        # DAS
        cfg.thisView = feval(cfg.physics.DASCallback, cfg.thisView, viewId, cfg)
   # print("After applying detection efficiency")
    #print(cfg.thisSubView)
    return cfg


if __name__ == "__main__":
    cfg = source_cfg("all_in_one.cfg")
    cfg.sim.startViewId = 0
    cfg.sim.stopViewId = 2
    cfg.sim.enableQuantumNoise = 1
    cfg.sim.subViewCount = 1
    cfg.det.totalNumCells = 2
    cfg.det.cosBetas = np.ones([cfg.det.totalNumCells, 1], dtype=np.single)
    cfg.det.betas = np.arccos(cfg.det.cosBetas)
    cfg = feval(cfg.protocol.spectrumCallback, cfg)

    cfg.thisSubView = np.float32(np.random.random([cfg.det.totalNumCells, cfg.sim.Evec.size])*100)
    cfg.thisSubView[1:4, 3:5] = 1
    viewId = 0
    subViewId = 0

    check_value(cfg.sim.Evec)
    check_value(cfg.thisSubView, row=0, plot=True)

    cfg = Detection_EI(cfg, viewId, subViewId)
    check_value(cfg.sim.Wvec, row=0)
    check_value(cfg.thisView, plot=True)
    
    i got this curve (attached) for these commands (    
check_value(cfg.sim.Evec)
    check_value(cfg.thisSubView, row=0, plot=True)
    )
     but for the lasts 3 commands i got this error:
     Traceback (most recent call last):
  File "/home/hassan/Downloads/straight/Detection_EI.py", line 120, in <module>
    cfg = Detection_EI(cfg, viewId, subViewId)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hassan/Downloads/straight/Detection_EI.py", line 69, in Detection_EI
    cfg.thisSubView = feval(cfg.physics.crosstalkCallback, cfg.thisSubView, cfg)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hassan/anaconda3/lib/python3.12/site-packages/gecatsim/pyfiles/CommonTools.py", line 41, in feval
    return eval(eval_name)(*args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hassan/anaconda3/lib/python3.12/site-packages/gecatsim/pyfiles/CalcCrossTalk.py", line 23, in CalcCrossTalk
    outView = np.reshape(thisView,
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/hassan/.local/lib/python3.12/site-packages/numpy/core/fromnumeric.py", line 285, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hassan/.local/lib/python3.12/site-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 400 into shape (900,16,200)

when i tried to change one of the energy count also this changes
 any help please to resolve this issue?
 and by the way, how can i determine the number or the flux of the primary beam ?
 
 regards
