### ISSUE TITLE
Access violation when running simulation

### ISSUE THREAD

**Issue by ltldlzltl** [xcist/main#2]
Hi guys, 

I am trying to simulate some CBCT projection data with XCIST recently and I started with the Adult_Male_Standard_Lung_Phantom provided in xcist/phantoms-voxelized. Much to my disappointment, I got some issues with memory access. I'm not quite sure if there is something wrong with my code or XCIST itself. 

Here is my simulation code
```python
import os
import catsim as xc
##--------- Initialize 
ct = xc.CatSim("FI_sim/cfg/Phantom_malelung")

##--------- Make changes to parameters or load other cfg files (optional)
output_folder = "./FI_sim/output/test_malelung/"
if not os.path.exists(output_folder):
    os.mkdir(output_folder)
ct.resultsName = output_folder + "result"

##--------- Run simulation
ct.run_all()  # run the scans defined by protocol.scanTypes
```
Phantom configuration
```python
# Phantom
phantom.callback = "Phantom_Voxelized"      # name of function that reads and models phantom
phantom.projectorCallback = "C_Projector_Voxelized" # name of function that performs projection through phantom
phantom.filename = './phantoms-voxelized/Adult_Male_Standard_Lung_Phantom/adult_male_standard_lung.json'
phantom.centerOffset = [0.0, 0.0, 0.0]      # offset of phantom center relative to origin (in mm)
phantom.scale = 1.0                         # re-scale the size of phantom
```
Terminal output
```terminal
Airscan
Loading GEANT4/EDLP97 cross section database...compton..rayleigh..photo..scatter..form..done
Scan sim time: 4.1 s
Offset scan
Scan sim time: 1.0 s
Phantom scan
Backend TkAgg is interactive backend. Turning interactive mode on.
in C> Preparing to allocate memory for material volume data...
in C> Allocated memory for image volume for material  1
in C> Copying data for material  1 into C memory...in C>  done.
in C> Allocated memory for image volume for material  2
in C> Copying data for material  2 into C memory...Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\catsim\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Administrator\anaconda3\envs\catsim\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.10.1336267007\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.10.1336267007\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main        
    run()
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.10.1336267007\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file    
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\Administrator\anaconda3\envs\catsim\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Administrator\anaconda3\envs\catsim\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Administrator\anaconda3\envs\catsim\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "e:\Tianling Lyu\CatSim\code\FI_sim\scripts\simulate_super0_malelung.py", line 25, in <module>
    ct.run_all()  # run the scans defined by protocol.scanTypes
  File "C:\Users\Administrator\anaconda3\envs\catsim\lib\site-packages\catsim\CatSim.py", line 28, in run_all
    cfg = self.phantom_scan(cfg)
  File "C:\Users\Administrator\anaconda3\envs\catsim\lib\site-packages\catsim\CatSim.py", line 52, in phantom_scan
    cfg = one_scan(cfg)
  File "C:\Users\Administrator\anaconda3\envs\catsim\lib\site-packages\catsim\OneScan.py", line 39, in one_scan
    cfg = feval(cfg.phantom.callback, cfg)
  File "C:\Users\Administrator\anaconda3\envs\catsim\lib\site-packages\catsim\CommonTools.py", line 30, in feval
    return eval("md."+funcName)(*args)
  File "C:\Users\Administrator\anaconda3\envs\catsim\lib\site-packages\catsim\Phantom_Voxelized.py", line 59, in Phantom_Voxelized
    set_voxelized_volume(cfg, volumeData, volumeDims, offsets, voxelsize, xyMask, materialIndex, numberOfMaterials)
  File "C:\Users\Administrator\anaconda3\envs\catsim\lib\site-packages\catsim\Phantom_Voxelized.py", line 89, in set_voxelized_volume
    offsets[0], offsets[1], offsets[2], voxelsize[0], voxelsize[2], xyMask, materialIndex, numberOfMaterials)
OSError: exception: access violation writing 0x000001945B5C8000
```
Is there any advice to run simulations on those lung phantoms? Thanks a lot in advance.

Best regards, 
Tianling Lyu

**Comment by ltldlzltl** [comment]
This issue seems to be related to the integer upper bound. 
```cpp
// clib_build/src/voxelized_projector.cpp: line 196-197
unsigned long phantom_num_voxels_this_material  = (unsigned long)dims[0]*(unsigned long)dims[1]*(unsigned long)dims[2];
unsigned long required_memory_size_this_material  = phantom_num_voxels_this_material *(unsigned long)sizeof(float);
```
For material 2 in the male lung phantom, the voxel number is 1,444,060,800 and the required memory size would be 5,776,243,200 which exceeds the upper bound of `unsigned long` on my PC. 
The code works after I changed those `unsigned long` to `unsigned long long`.

**Comment by MingyeWu** [comment]
Thank you for the advice. I have updated the code with "long long".
