### ISSUE TITLE
Instructions of installation and testing fail

### ISSUE THREAD

**Issue by AnderBiguri** [xcist/main#29]
If I follow the instructions for installation at: https://github.com/xcist/documentation/wiki/CatSim-Python-setup (command line installation) and try to run the demo, as seen in the link, the code errors (both Windows and Linux) 

```
 python .\Sim_Sample.py
***WARNING: d:\catSim\cathy-samplessss does not exist.
Airscan
Scan sim time: 1.8 s
Offset scan
Scan sim time: 0.2 s
Phantom scan
Traceback (most recent call last):
  File "D:\CatSim\examples\Sim_Sample.py", line 23, in <module>
    ct.run_all()  # run the scans defined by protocol.scanTypes
    ^^^^^^^^^^^^
  File "C:\Users\Ander\AppData\Roaming\Python\Python311\site-packages\catsim\pyfiles\CatSim.py", line 26, in run_all
    cfg = self.phantom_scan(cfg)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ander\AppData\Roaming\Python\Python311\site-packages\catsim\pyfiles\CatSim.py", line 50, in phantom_scan
    cfg = one_scan(cfg)
          ^^^^^^^^^^^^^
  File "C:\Users\Ander\AppData\Roaming\Python\Python311\site-packages\catsim\pyfiles\OneScan.py", line 38, in one_scan
    cfg = feval(cfg.phantom.callback, cfg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ander\AppData\Roaming\Python\Python311\site-packages\catsim\pyfiles\CommonTools.py", line 41, in feval
    return eval(eval_name)(*args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ander\AppData\Roaming\Python\Python311\site-packages\catsim\pyfiles\Phantom_Voxelized.py", line 11, in Phantom_Voxelized
    cfg.phantom.filename = my_path.find('phantom', cfg.phantom.filename, '')
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ander\AppData\Roaming\Python\Python311\site-packages\catsim\pyfiles\CommonTools.py", line 121, in find
    raise Exception("Cannot find %s or %s%s" %(filename, filename, extension))
Exception: Cannot find CatSim_logo_1024.json or CatSim_logo_1024.json
```

I can see that the files themselves do exist in the `catsim/phatom/CatSimLogo_1024` folder but the code does not seem to be able to identify this. 

I tried to figure out in which part are the paths that look for the phantom set, but I still don't have a good grasp of the functionality, so apologies for not finding the error.

**Comment by zhangjy-ge** [comment]
This seems to be an installation bug, in which the CatSim_logo_* was not copied to the desired locations. The bug has been fixed and you may need to re-install xcist to make it work.

**Comment by AnderBiguri** [comment]
Thanks @zhangjy-ge ;)
